# Generated by Django 4.2.2 on 2023-06-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestroMonitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=255, unique=True)),
                ('csv_file', models.FileField(upload_to='reports/')),
                ('isProcessing', models.BooleanField(default=False)),
                ('isGenerated', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='storebusinesshours',
            name='day',
            field=models.IntegerField(),
        ),
    ]
